name: lint&build 

on:
  push:
    branches: [ main ]

env:
  IMAGE_NAME: hello-world-app
  DOCKERHUB_REPO: ${{ secrets.DOCKERHUB_USERNAME }}/hello-world-app

jobs:
  lint:
    name: Lint Code
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '20'

      - name: Install dependencies
        run: |
          cd app
          npm ci

      - name: Run ESLint
        run: |
          cd app
          npm run lint

  build-and-push:
    name: Build & Push Docker Image
    needs: lint
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build Docker image
        run: docker build -t $DOCKERHUB_REPO:latest .

      - name: Push to Docker Hub
        run: docker push $DOCKERHUB_REPO:latest
